Modal buy now vadim
KostiantynU/project-6__ice-cream pull request #19
Opened 2023-01-16 01:46 UTC by VadBorovec

Додає модалку на Buy Now
Скрипт на Disabled button
В секції Hero-Header робив прив'язку до своєї модалки.
В форму добавив різні типи валідації та псевдокласи стану.

2023-01-16 01:54 UTC, VadBorovec commented
щойно побачив що Микола також робив пулл на секцію Hero-Header. Якщо будуть конфлікти, при потребі зможу зробити без змін в секції Hero-Header. Там буквально одні фразу змінив на кнопці:
` js-open-modal" data-modal="modal-buy-now"` замість `data-menu-open`

2023-01-16 01:56 UTC, VadBorovec commented
скрипт добавив в кінці своєї секції...потрібно буде перенести на index.html

2023-01-16 07:41 UTC, KostiantynU requested changes
1. В модалці Н2 - Н2 тільки для секцій, давай тег Р
2. Поправити картинки - одна і та ж картинка вказана для Х2
3. Сама картинка має розмір 128х132. Хоча у тега імж картинки вкладені всі вірного розміру. Я знайшов причину такоїх поведінки - бордер для Р забирає 2рх зліва, 2рх зправа, і картинка стає 132рх, як по макету. Може той бордер дати, лішці?
4. Кнопка бачу неактивна, але якщо вибрати морозиво - так і залишається. Схоже ще не все підключено? У твоїй гілці працює? Бо я в ній і дивлюсь...

2023-01-17 01:25 UTC, VadBorovec commented
1. В модалці Н2 - Н2 тільки для секцій, давай тег Р
замінив

2. Поправити картинки - одна і та ж картинка вказана для Х2
виправив

3. Сама картинка має розмір 128х132. Хоча у тега імж картинки вкладені всі вірного розміру. Я знайшов причину такоїх поведінки - бордер для Р забирає 2рх зліва, 2рх зправа, і картинка стає 132рх, як по макету. Може той бордер дати, лішці?
не вийшло, може завтра на свіжу голову спробую

4. Кнопка бачу неактивна, але якщо вибрати морозиво - так і залишається. Схоже ще не все підключено? У твоїй гілці працює? Бо я в ній і дивлюсь...
Кнопка активується на заповнення інпуту - Ім'я

Пробіл між секціями Контакти / Футер прибрав

2023-01-17 14:30 UTC, VadBorovec reviewed
внесені правки

2023-01-17 16:55 UTC, merged