About/advantages
KostiantynU/project-6__ice-cream pull request #8
Opened 2023-01-14 20:44 UTC by DmytroRiabchenko

Прошу провернить мою работу,спасибо

2023-01-15 20:49 UTC, KostiantynU commented
1. Дати падінг-топ і паддінг-боттом на секцію, відповідно до розмірів в'юпорта, згідно з макетом. Одразу забереш маржини з країніх елементів.
2. Тег Р не стилізуй - дай класс своїм абзацам, потім стилі.
3. Лайн-хейти не задаються в пікселях. Це завжди значення з двома цифрами після крапки. Значення - результат ділення того що вказано в макеті на розмір шрифту. Наприклад для 320рх вказано лайн-хейт 22рх. Ділиш 22 на фонт-сайз 18 = 1.22 пишеш в лайн-хейт.
4. Перезібрати картинки відповідно до макету, відповідно до неохідного розмірю в'юпорта - для мобілки грузиться картинка 660х660, а для таблету 330х330
5. Абзац під корівкою (дивлюсь на 320рх) - лайн-хейт у відсотках. Якщо вказано 176% = пиши 1.76;
6. Для другого абзацу лайнхейт 1.64
7. В Н3 ти вставив 721. Що семантично важливого в цій цифрі? Чи доцільно тут робити Н3?
8. Тег лейбл, без форми?
9. Для 480рх традішн енд лав фонт-вейт 800, чуть забагато, 700 за макетом
10. Планшет, список з текстом, маржин-боттом на тег Р даний - поставити на лі. Перевірь всі в'юпорти і перестав на лішки
11. фонт-вейт 400 не треба вказувати - це дефолт, малюється браузером. Все що не 400 треба визначати
12. Планшет, текст Aliquam ac dui vel dui - розмір змінити, леттер-спасінг 0.04 (не треба вказувати - візьметься від боді)
13. Десктоп, корова і зправа абзаци з кнопкою - по макету чуть нижче стоять. Або подумай як опустити ту юл з абзацами, або будем надіятись що не замітять :-)
14. Десктоп, текст Aliquam ac dui vel dui - леттер-спасінг 0.02 вказати. Для таблета, в макеті, леттерспасінг не має. А для десктопа є

2023-01-15 20:49 UTC, KostiantynU requested changes
Комент вписав - перевір

2023-01-15 21:02 UTC, DmytroRiabchenko commented
Исправил всё кроме 4 и 13 пункта

2023-01-16 22:12 UTC, KostiantynU approved these changes
Ііі, поїхали

2023-01-16 22:14 UTC, merged